export const ROLES = {
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  DOCTOR: "DOCTOR",
  NURSE: "NURSE",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
};

export const PERMISSIONS = {
  OVERVIEW_READ: "overview:read",

  STAFF_READ: "staff:read",
  STAFF_MANAGE: "staff:manage",

  DEPARTMENT_READ: "department:read",
  DEPARTMENT_MANAGE: "department:manage",

  PATIENT_READ: "patient:read",
  PATIENT_MANAGE: "patient:manage",

  ROOM_READ: "room:read",
  ROOM_MANAGE: "room:manage",

  EMERGENCY_READ: "emergency:read",
  EMERGENCY_MANAGE: "emergency:manage",

  APPOINTMENT_READ: "appointment:read",
  APPOINTMENT_MANAGE: "appointment:manage",

  ADMISSION_READ: "admission:read",
  ADMISSION_MANAGE: "admission:manage",

  SURGERY_READ: "surgery:read",
  SURGERY_MANAGE: "surgery:manage",

  REPORT_READ: "report:read",

  INTELLIGENCE_READ: "intelligence:read",

  MESSAGE_READ: "message:read",
  MESSAGE_SEND: "message:send",
};

export const ROLE_PERMISSIONS = {
  [ROLES.HOSPITAL_ADMIN]: [
    PERMISSIONS.OVERVIEW_READ,

    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_MANAGE,

    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,

    PERMISSIONS.ROOM_READ,
    PERMISSIONS.ROOM_MANAGE,

    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_MANAGE,

    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,

    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.ADMISSION_MANAGE,

    PERMISSIONS.SURGERY_READ,
    PERMISSIONS.SURGERY_MANAGE,

    PERMISSIONS.REPORT_READ,
    PERMISSIONS.INTELLIGENCE_READ,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.DEPARTMENT_MANAGER]: [
    PERMISSIONS.OVERVIEW_READ,

    PERMISSIONS.STAFF_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,

    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.ROOM_READ,

    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.SURGERY_READ,

    PERMISSIONS.REPORT_READ,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.OVERVIEW_READ,

    PERMISSIONS.STAFF_READ,
    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,

    PERMISSIONS.ROOM_READ,

    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.SURGERY_READ,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.OVERVIEW_READ,

    PERMISSIONS.STAFF_READ,
    PERMISSIONS.DEPARTMENT_READ,

    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,

    PERMISSIONS.ROOM_READ,

    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.ADMISSION_READ,

    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],
};

export function getPermissionsByRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(userPermissions = [], requiredPermission) {
  if (!requiredPermission) return true;

  return userPermissions.includes(requiredPermission);
}

export function hasAnyPermission(userPermissions = [], requiredPermissions = []) {
  if (!requiredPermissions.length) return true;

  return requiredPermissions.some((permission) =>
    userPermissions.includes(permission),
  );
}