export const ROLES = {
  PLATFORM_ADMIN: "PLATFORM_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  ADMINISTRATOR: "ADMINISTRATOR",
  DOCTOR: "DOCTOR",
  CLINIC_DOCTOR: "CLINIC_DOCTOR",
  CLINIC_ADMIN: "CLINIC_ADMIN",
  CLINIC_STAFF: "CLINIC_STAFF",
  PHARMACIST: "PHARMACIST",
  BILLING_STAFF: "BILLING_STAFF",
  NURSE: "NURSE",
  TECHNICIAN: "TECHNICIAN",
  DEPARTMENT_MANAGER: "DEPARTMENT_MANAGER",
};

export const SIGN_IN_ROLES = [];

export const ROLE_DEFAULT_LANDING = {
  [ROLES.HOSPITAL_ADMIN]: {
    domain: "overview",
    subsection: null,
    function: "command",
  },
  [ROLES.ADMINISTRATOR]: {
    domain: "overview",
    subsection: null,
    function: "command",
  },
  [ROLES.DOCTOR]: {
    domain: "operations",
    subsection: "clinic-operations",
    function: "clinic-doctor-dashboard",
  },
  [ROLES.CLINIC_DOCTOR]: {
    domain: "operations",
    subsection: "clinic-operations",
    function: "clinic-doctor-dashboard",
  },
  [ROLES.CLINIC_ADMIN]: {
    domain: "operations",
    subsection: "clinic-operations",
    function: "clinic-doctor-dashboard",
  },
};

export const PERMISSIONS = {
  AUTH_ME: "auth:me",
  WORKSPACE_SELECT: "workspace:select",
  OVERVIEW_READ: "overview:read",

  HOSPITAL_READ: "hospital:read",
  HOSPITAL_MANAGE: "hospital:manage",

  STAFF_READ: "staff:read",
  STAFF_MANAGE: "staff:manage",

  DEPARTMENT_READ: "department:read",
  DEPARTMENT_MANAGE: "department:manage",

  PATIENT_READ: "patient:read",
  PATIENT_MANAGE: "patient:manage",

  ROOM_READ: "room:read",
  ROOM_MANAGE: "room:manage",

  EMERGENCY_READ: "emergency:read",
  EMERGENCY_MANAGE: "emergency:manage",

  APPOINTMENT_READ: "appointment:read",
  APPOINTMENT_MANAGE: "appointment:manage",

  FOLLOW_UP_READ: "followup:read",
  FOLLOW_UP_CREATE: "followup:create",
  FOLLOW_UP_UPDATE: "followup:update",

  ADMISSION_READ: "admission:read",
  ADMISSION_MANAGE: "admission:manage",

  SURGERY_READ: "surgery:read",
  SURGERY_MANAGE: "surgery:manage",

  REPORT_READ: "report:read",

  INTELLIGENCE_READ: "intelligence:read",

  MESSAGE_READ: "message:read",
  MESSAGE_SEND: "message:send",
  MESSAGE_GROUP_CREATE: "message:group:create",

  CLINIC_READ: "clinic:read",
  CLINIC_MANAGE: "clinic:manage",
  DOCTOR_READ: "doctor:read",
  DOCTOR_MANAGE: "doctor:manage",
  CONSULTATION_READ: "consultation:read",
  CONSULTATION_CREATE: "consultation:create",
  CONSULTATION_UPDATE: "consultation:update",

  PHARMACY_READ: "pharmacy:read",
  PHARMACY_MANAGE: "pharmacy:manage",
  PRESCRIPTION_READ: "prescription:read",
  PRESCRIPTION_CREATE: "prescription:create",
  PRESCRIPTION_DISPENSE: "prescription:dispense",
  MEDICATION_READ: "medication:read",
  MEDICATION_MANAGE: "medication:manage",

  BILLING_READ: "billing:read",
  BILLING_CREATE: "billing:create",
  BILLING_UPDATE: "billing:update",
  BILLING_PAYMENT_RECORD: "billing:payment:record",
  BILLING_REFUND_CREATE: "billing:refund:create",
  BILLING_REPORT_READ: "billing:report:read",
};

export const ROLE_PERMISSIONS = {
  [ROLES.PLATFORM_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.HOSPITAL_ADMIN]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.ROOM_MANAGE,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.EMERGENCY_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.BILLING_PAYMENT_RECORD,
    PERMISSIONS.BILLING_REFUND_CREATE,
    PERMISSIONS.BILLING_REPORT_READ,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.ADMISSION_MANAGE,
    PERMISSIONS.SURGERY_READ,
    PERMISSIONS.SURGERY_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.INTELLIGENCE_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_GROUP_CREATE,
  ],

  [ROLES.ADMINISTRATOR]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.DOCTOR]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.FOLLOW_UP_READ,
    PERMISSIONS.FOLLOW_UP_CREATE,
    PERMISSIONS.FOLLOW_UP_UPDATE,
    PERMISSIONS.SURGERY_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.CONSULTATION_READ,
    PERMISSIONS.CONSULTATION_CREATE,
    PERMISSIONS.CONSULTATION_UPDATE,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.PRESCRIPTION_CREATE,
  ],

  [ROLES.CLINIC_DOCTOR]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.SURGERY_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.INTELLIGENCE_READ,
  ],

  [ROLES.CLINIC_ADMIN]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.CLINIC_MANAGE,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.DOCTOR_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.CONSULTATION_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_GROUP_CREATE,
  ],

  [ROLES.CLINIC_STAFF]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.CLINIC_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_MANAGE,
    PERMISSIONS.CONSULTATION_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.PHARMACIST]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.PHARMACY_MANAGE,
    PERMISSIONS.PRESCRIPTION_READ,
    PERMISSIONS.PRESCRIPTION_DISPENSE,
    PERMISSIONS.MEDICATION_READ,
    PERMISSIONS.MEDICATION_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.BILLING_STAFF]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.BILLING_UPDATE,
    PERMISSIONS.BILLING_PAYMENT_RECORD,
    PERMISSIONS.BILLING_REFUND_CREATE,
    PERMISSIONS.BILLING_REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.DEPARTMENT_MANAGER]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.SURGERY_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.NURSE]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.DEPARTMENT_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.PATIENT_MANAGE,
    PERMISSIONS.ROOM_READ,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],

  [ROLES.TECHNICIAN]: [
    PERMISSIONS.AUTH_ME,
    PERMISSIONS.WORKSPACE_SELECT,
    PERMISSIONS.OVERVIEW_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.EMERGENCY_READ,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
  ],
};

export function getPermissionsByRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

export function getRoleLanding(role) {
  return ROLE_DEFAULT_LANDING[role] || ROLE_DEFAULT_LANDING[ROLES.HOSPITAL_ADMIN];
}

export function usesRolePlaceholder(role) {
  return role === ROLES.CLINIC_DOCTOR || role === ROLES.DOCTOR;
}

export function hasPermission(userPermissions = [], requiredPermission) {
  if (!requiredPermission) return true;

  return userPermissions.includes(requiredPermission);
}

export function hasAnyPermission(userPermissions = [], requiredPermissions = []) {
  if (!requiredPermissions.length) return true;

  return requiredPermissions.some((permission) =>
    userPermissions.includes(permission),
  );
}
