const DRAFT_RULE_GOVERNANCE = Object.freeze({
  version: "0.1.0-prototype",
  status: "draft",
  guideline:
    "Thresholds supplied in the healthcare specification; exact guideline versions were not supplied.",
  reviewedAt: null,
  reviewedBy: null,
  appliesTo: "Clinician-facing adult prototype unless a measurement states otherwise.",
  exclusions:
    "Pediatric, pregnancy, frailty, ethnicity, renal-disease, assay-specific, and individualized treatment-target exceptions remain incomplete.",
});

function draftRule(rule) {
  return {
    ...rule,
    governance: {
      ...DRAFT_RULE_GOVERNANCE,
      ...(rule.governance || {}),
    },
  };
}

function measurement({
  id,
  clinicalName,
  patientFriendlyName,
  unit,
  referenceRange,
  freshness,
  loincCodes = [],
  aliases = [],
  rule,
  trend,
  contextualModifiers = [],
  sourceTypes = [],
  clinicianObservation,
  patientMessage,
  clinicianOnly = false,
  validatedResultOnly = false,
}) {
  return {
    id,
    clinicalName,
    patientFriendlyName,
    unit,
    referenceRange,
    freshness,
    loincCodes,
    aliases,
    rule: draftRule(rule),
    trend,
    contextualModifiers,
    sourceTypes,
    clinicianObservation,
    patientMessage,
    clinicianOnly,
    validatedResultOnly,
  };
}

export const PROVISIONAL_RULE_GOVERNANCE = DRAFT_RULE_GOVERNANCE;

export const PATIENT_SYSTEM_CLINICAL_CONFIG = Object.freeze({
  overview: {
    id: "overview",
    label: "Whole-body Overview",
    shortLabel: "Overview",
    summary:
      "A prioritized orientation view across connected clinical records and current observations.",
    anatomy: {
      represented: true,
      status: "exterior-only",
      message: "Exterior body view only; embedded organs are hidden.",
    },
    measurements: [],
  },
  cardiovascular: {
    id: "cardiovascular",
    label: "Cardiovascular",
    shortLabel: "Cardiovascular",
    summary:
      "Heart and blood vessel function, including rhythm, pressure, and circulation.",
    anatomy: {
      represented: true,
      status: "partial",
      message:
        "Partial 3D representation: only the heart mesh present in the current model can be highlighted.",
    },
    measurements: [
      measurement({
        id: "blood-pressure",
        clinicalName: "Blood pressure",
        patientFriendlyName: "Blood pressure",
        unit: "mmHg",
        referenceRange: "<120/<80",
        freshness: { inpatientHours: 24, outpatientDays: 90 },
        loincCodes: ["85354-9", "55284-4"],
        aliases: ["blood pressure", "systolic blood pressure", "diastolic blood pressure"],
        rule: { type: "blood-pressure" },
        trend: {
          windowDays: 90,
          meaningfulChange: { systolic: 10, diastolic: 10 },
          minimumPointsForMeaningful: 3,
          description: "A sustained shift greater than 10 mmHg requires review.",
        },
        contextualModifiers: ["symptoms", "pregnancy", "CKD", "diabetes", "treatment target"],
        sourceTypes: ["vital-sign", "device"],
        clinicianObservation: "Blood pressure reading outside the provisional reference range.",
        patientMessage: "A blood pressure reading is outside the reference range used for this view.",
      }),
      measurement({
        id: "heart-rate",
        clinicalName: "Resting heart rate",
        patientFriendlyName: "Heart rate",
        unit: "bpm",
        referenceRange: "60-100",
        freshness: { inpatientHours: 24, outpatientDays: 90 },
        loincCodes: ["8867-4"],
        aliases: ["heart rate", "pulse", "resting heart rate"],
        rule: { type: "heart-rate" },
        trend: {
          windowDays: 90,
          meaningfulChange: 15,
          meaningfulInclusive: false,
          description: "A baseline shift greater than 15 bpm requires review.",
        },
        contextualModifiers: ["age", "fitness level", "beta-blockers"],
        sourceTypes: ["vital-sign", "device", "wearable-derived"],
        clinicianObservation: "Heart-rate reading outside the provisional reference range.",
        patientMessage: "A heart-rate reading is outside the reference range used for this view.",
      }),
      measurement({
        id: "ldl-cholesterol",
        clinicalName: "LDL cholesterol",
        patientFriendlyName: "LDL cholesterol",
        unit: "mg/dL",
        referenceRange: "<100",
        freshness: { outpatientDays: 365 },
        loincCodes: ["13457-7", "2089-1", "18262-6"],
        aliases: ["ldl", "ldl cholesterol"],
        rule: { type: "ldl" },
        trend: { windowDays: 365 },
        contextualModifiers: ["individual treatment target", "existing cardiovascular disease"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "LDL cholesterol result outside the provisional reference range.",
        patientMessage: "An LDL cholesterol result is outside the reference range used for this view.",
      }),
      measurement({
        id: "hdl-cholesterol",
        clinicalName: "HDL cholesterol",
        patientFriendlyName: "HDL cholesterol",
        unit: "mg/dL",
        referenceRange: ">=60; low <40 male or <50 female",
        freshness: { outpatientDays: 365 },
        loincCodes: ["2085-9"],
        aliases: ["hdl", "hdl cholesterol"],
        rule: { type: "hdl" },
        trend: { windowDays: 365 },
        contextualModifiers: ["recorded sex"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "HDL cholesterol result outside the provisional reference range.",
        patientMessage: "An HDL cholesterol result is outside the reference range used for this view.",
      }),
      measurement({
        id: "troponin",
        clinicalName: "Troponin",
        patientFriendlyName: "Heart muscle marker",
        unit: "assay-specific",
        referenceRange: "Assay-specific laboratory upper reference limit required",
        freshness: { inpatientHours: 6, outpatientDays: 1 },
        loincCodes: ["6598-7", "42757-5", "89579-7"],
        aliases: ["troponin", "troponin i", "troponin t", "high sensitivity troponin"],
        rule: { type: "reported-upper-limit" },
        contextualModifiers: ["assay", "renal function", "symptoms", "ECG"],
        sourceTypes: ["laboratory"],
        clinicianObservation:
          "Troponin result above the reported assay reference limit; correlate clinically.",
        patientMessage:
          "A heart-related laboratory result requires interpretation by the care team.",
        clinicianOnly: true,
      }),
      measurement({
        id: "nt-probnp",
        clinicalName: "NT-proBNP",
        patientFriendlyName: "Heart strain marker",
        unit: "pg/mL",
        referenceRange: "Age-, renal-, and obesity-dependent",
        freshness: { inpatientHours: 24, outpatientDays: 180 },
        loincCodes: ["33762-6"],
        aliases: ["nt-probnp", "nt probnp", "n-terminal probnp"],
        rule: { type: "requires-applicable-rule" },
        contextualModifiers: ["age", "renal function", "obesity"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "NT-proBNP result recorded; an applicable interpretation rule is required.",
        patientMessage: "This laboratory result requires interpretation by the care team.",
        clinicianOnly: true,
      }),
      measurement({
        id: "weight",
        clinicalName: "Body weight",
        patientFriendlyName: "Weight",
        unit: "kg",
        referenceRange: "Individual baseline or treatment target required",
        freshness: { inpatientHours: 24, outpatientDays: 90 },
        loincCodes: ["29463-7", "8335-2", "3141-9"],
        aliases: ["body weight", "weight"],
        rule: { type: "weight-change" },
        trend: {
          windowDays: 90,
          meaningfulChange: 2,
          meaningfulChangeDays: 3,
          meaningfulDirection: "increase",
          meaningfulInclusive: false,
          description: "A gain greater than 2 kg over 3 days requires clinician review.",
        },
        sourceTypes: ["vital-sign", "medical-profile", "patient-reported"],
        clinicianObservation: "Weight change from the patient's prior recorded value.",
        patientMessage: "Weight is compared with prior recorded values when dates are available.",
      }),
    ],
  },
  respiratory: {
    id: "respiratory",
    label: "Respiratory",
    shortLabel: "Respiratory",
    summary: "Lung function and oxygen exchange.",
    anatomy: {
      represented: true,
      status: "partial",
      message:
        "Partial 3D representation: only the lung meshes present in the current model can be highlighted.",
    },
    measurements: [
      measurement({
        id: "respiratory-rate",
        clinicalName: "Respiratory rate",
        patientFriendlyName: "Breathing rate",
        unit: "breaths/min",
        referenceRange: "12-20",
        freshness: { inpatientHours: 24, outpatientDays: 1 },
        loincCodes: ["9279-1"],
        aliases: ["respiratory rate", "breathing rate"],
        rule: { type: "respiratory-rate" },
        sourceTypes: ["vital-sign", "device"],
        clinicianObservation: "Respiratory-rate reading outside the provisional reference range.",
        patientMessage: "A breathing-rate reading is outside the reference range used for this view.",
      }),
      measurement({
        id: "oxygen-saturation",
        clinicalName: "Oxygen saturation (SpO2)",
        patientFriendlyName: "Oxygen level",
        unit: "%",
        referenceRange: ">=95 general; individualized target required when applicable",
        freshness: { inpatientHours: 1, outpatientHours: 24 },
        loincCodes: ["59408-5", "2708-6"],
        aliases: ["spo2", "oxygen saturation", "pulse oximetry"],
        rule: {
          type: "oxygen-saturation",
          governance: {
            exclusions:
              "COPD and altitude-adjusted targets require an individualized target. The source document's COPD/non-COPD escalation wording is inconsistent and requires Clinical Safety Officer approval before production alerting.",
          },
        },
        trend: {
          windowDays: 30,
          meaningfulChange: 3,
          meaningfulDirection: "decrease",
          meaningfulInclusive: false,
          description: "A drop greater than 3 percentage points from baseline requires review.",
        },
        contextualModifiers: ["individual target", "COPD", "altitude", "sustained reading"],
        sourceTypes: ["vital-sign", "device", "wearable-derived"],
        clinicianObservation: "Low oxygen saturation observed.",
        patientMessage: "An oxygen-level reading was lower than the target used for this view.",
      }),
      measurement({
        id: "peak-expiratory-flow",
        clinicalName: "Peak expiratory flow",
        patientFriendlyName: "Breath strength",
        unit: "% predicted or personal best",
        referenceRange: ">=80% predicted or personal best",
        freshness: { outpatientDays: 180 },
        loincCodes: ["6301-6"],
        aliases: ["peak expiratory flow", "peak flow", "pef"],
        rule: { type: "peak-flow-percent" },
        trend: {
          windowDays: 180,
          meaningfulChange: 20,
          meaningfulDirection: "decrease",
          meaningfulInclusive: false,
          description: "A drop greater than 20% from personal best requires review.",
        },
        contextualModifiers: ["age", "sex", "height", "personal best"],
        sourceTypes: ["pulmonary-function-test", "patient-reported"],
        clinicianObservation: "Peak expiratory flow below the applicable comparison value.",
        patientMessage: "A breathing-test result is below the comparison value used for this view.",
      }),
      measurement({
        id: "fev1-fvc",
        clinicalName: "FEV1/FVC ratio",
        patientFriendlyName: "Airflow ratio",
        unit: "ratio",
        referenceRange: "Age-dependent lower limit required",
        freshness: { outpatientDays: 365 },
        aliases: ["fev1/fvc", "fev1 fvc ratio", "airway obstruction ratio"],
        rule: { type: "reported-lower-limit" },
        trend: { windowDays: 180 },
        contextualModifiers: ["age-dependent lower limit"],
        sourceTypes: ["pulmonary-function-test"],
        clinicianObservation: "FEV1/FVC result outside the reported reference range.",
        patientMessage: "This breathing-test ratio requires interpretation by the care team.",
      }),
    ],
  },
  digestive: {
    id: "digestive",
    label: "Digestive",
    shortLabel: "Digestive",
    summary: "Digestion, nutrient absorption, and liver/pancreas function.",
    anatomy: {
      represented: true,
      status: "partial",
      message:
        "Partial 3D representation: only digestive meshes genuinely present in the current model can be highlighted.",
      productGap:
        "Future product gap: renal/urinary anatomy and clinical content are not represented; kidneys do not belong to this system.",
    },
    measurements: [
      measurement({
        id: "alt",
        clinicalName: "Alanine aminotransferase (ALT)",
        patientFriendlyName: "Liver enzyme (ALT)",
        unit: "U/L",
        referenceRange: "7-56",
        freshness: { outpatientDays: 180 },
        loincCodes: ["1742-6"],
        aliases: ["alt", "alanine aminotransferase"],
        rule: { type: "alt" },
        trend: {
          windowDays: 365,
          meaningfulFactor: 2,
          meaningfulDirection: "increase",
          description: "A rise greater than 2x the patient's baseline requires review.",
        },
        sourceTypes: ["laboratory"],
        clinicianObservation: "Liver enzyme result outside the provisional reference range.",
        patientMessage: "A liver-related laboratory result is outside the reference range used here.",
      }),
      measurement({
        id: "ast",
        clinicalName: "Aspartate aminotransferase (AST)",
        patientFriendlyName: "Liver enzyme (AST)",
        unit: "U/L",
        referenceRange: "10-40",
        freshness: { outpatientDays: 180 },
        loincCodes: ["1920-8"],
        aliases: ["ast", "aspartate aminotransferase"],
        rule: { type: "ast" },
        trend: {
          windowDays: 365,
          meaningfulFactor: 2,
          meaningfulDirection: "increase",
          description: "A rise greater than 2x the patient's baseline requires review.",
        },
        sourceTypes: ["laboratory"],
        clinicianObservation: "Liver enzyme result outside the provisional reference range.",
        patientMessage: "A liver-related laboratory result is outside the reference range used here.",
      }),
      measurement({
        id: "total-bilirubin",
        clinicalName: "Total bilirubin",
        patientFriendlyName: "Bilirubin",
        unit: "mg/dL",
        referenceRange: "0.1-1.2",
        freshness: { outpatientDays: 90 },
        loincCodes: ["1975-2"],
        aliases: ["total bilirubin", "bilirubin total"],
        rule: { type: "total-bilirubin" },
        trend: { windowDays: 365 },
        sourceTypes: ["laboratory"],
        clinicianObservation: "Bilirubin result outside the provisional reference range.",
        patientMessage: "A bilirubin result is outside the reference range used for this view.",
      }),
      measurement({
        id: "lipase",
        clinicalName: "Lipase",
        patientFriendlyName: "Pancreatic enzyme",
        unit: "U/L",
        referenceRange: "10-140",
        freshness: { inpatientHours: 24, outpatientDays: 90 },
        loincCodes: ["3040-3"],
        aliases: ["lipase"],
        rule: { type: "lipase" },
        trend: { windowDays: 365 },
        contextualModifiers: ["laboratory upper reference limit"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "Pancreatic enzyme result outside the provisional reference range.",
        patientMessage: "A pancreatic-enzyme result is outside the reference range used here.",
      }),
      measurement({
        id: "bmi",
        clinicalName: "Body mass index (BMI)",
        patientFriendlyName: "Body mass index",
        unit: "kg/m2",
        referenceRange: "18.5-24.9",
        freshness: { outpatientDays: 90 },
        loincCodes: ["39156-5"],
        aliases: ["body mass index", "bmi"],
        rule: { type: "bmi" },
        trend: {
          windowDays: 365,
          meaningfulPercent: 5,
          description: "A weight or BMI change greater than 5% over 6 months requires review.",
        },
        contextualModifiers: ["ethnicity-specific cutoff"],
        sourceTypes: ["calculated", "laboratory"],
        clinicianObservation: "BMI result outside the provisional reference range.",
        patientMessage: "Body mass index is outside the reference range used for this view.",
      }),
    ],
  },
  nervous: {
    id: "nervous",
    label: "Nervous",
    shortLabel: "Nervous",
    summary:
      "Brain, spinal cord, and nerve function including cognition, movement, and reflexes.",
    anatomy: {
      represented: true,
      status: "partial",
      message:
        "Partial 3D representation: the brain mesh is available; the spinal cord and peripheral nerves are not yet modeled.",
    },
    measurements: [
      measurement({
        id: "gcs",
        clinicalName: "Glasgow Coma Scale",
        patientFriendlyName: "Consciousness assessment",
        unit: "3-15",
        referenceRange: "15 expected",
        freshness: { inpatientHours: 1, outpatientHours: 24 },
        aliases: ["glasgow coma scale", "gcs"],
        rule: { type: "gcs" },
        trend: {
          windowDays: 2,
          meaningfulChange: 2,
          description: "A drop of 2 or more points from baseline requires immediate clinician review.",
        },
        sourceTypes: ["clinician-assessment"],
        clinicianObservation: "Consciousness assessment requires clinician review.",
        patientMessage: "This assessment must be interpreted by the care team.",
        clinicianOnly: true,
      }),
      measurement({
        id: "cognitive-score",
        clinicalName: "MoCA/MMSE",
        patientFriendlyName: "Cognitive assessment",
        unit: "0-30",
        referenceRange: "Age- and education-dependent",
        freshness: { outpatientDays: 365 },
        aliases: ["moca", "mmse", "mini mental state examination", "montreal cognitive assessment"],
        rule: { type: "requires-applicable-rule" },
        trend: {
          windowDays: 1095,
          meaningfulChange: 3,
          description: "A change of 3 or more MMSE points requires clinician review.",
        },
        contextualModifiers: ["age", "education"],
        sourceTypes: ["clinician-assessment", "questionnaire"],
        clinicianObservation: "Cognitive score recorded; age and education context are required.",
        patientMessage: "A single cognitive score does not provide a diagnosis.",
        clinicianOnly: true,
      }),
      measurement({
        id: "nihss",
        clinicalName: "NIH Stroke Scale (NIHSS)",
        patientFriendlyName: "Neurological assessment",
        unit: "0-42",
        referenceRange: "Clinician-only instrument",
        freshness: { inpatientHours: 1 },
        aliases: ["nihss", "nih stroke scale", "national institutes of health stroke scale"],
        rule: { type: "requires-clinician-interpretation" },
        sourceTypes: ["clinician-assessment"],
        clinicianObservation: "NIHSS score recorded; review the complete clinician assessment.",
        patientMessage: "This assessment must be interpreted by the care team.",
        clinicianOnly: true,
      }),
    ],
  },
  musculoskeletal: {
    id: "musculoskeletal",
    label: "Musculoskeletal",
    shortLabel: "Musculoskeletal",
    summary: "Bones, joints, and muscles supporting movement and structure.",
    anatomy: {
      represented: false,
      status: "not-represented",
      message:
        "This system is not yet represented in the 3D model. Clinical information is shown in text.",
    },
    measurements: [
      measurement({
        id: "pain-score",
        clinicalName: "Pain score (NRS)",
        patientFriendlyName: "Pain level",
        unit: "0-10",
        referenceRange: "0 none; 1-3 mild; 4-6 moderate; 7-10 severe",
        freshness: { inpatientHours: 24, outpatientHours: 24 },
        loincCodes: ["72514-3", "38208-5"],
        aliases: ["pain score", "pain severity", "nrs pain"],
        rule: { type: "pain-score" },
        trend: {
          windowDays: 28,
          meaningfulChange: 2,
          description: "A change of 2 or more points requires review.",
        },
        sourceTypes: ["patient-reported"],
        clinicianObservation: "Patient-reported pain score recorded.",
        patientMessage: "Your reported pain level is shown with its date and source.",
      }),
      measurement({
        id: "dexa-t-score",
        clinicalName: "DEXA T-score",
        patientFriendlyName: "Bone-density result",
        unit: "SD",
        referenceRange: ">=-1.0 expected range",
        freshness: { outpatientDays: 730 },
        aliases: ["dexa t-score", "dexa t score", "bone density t-score", "t-score"],
        rule: { type: "dexa-t-score" },
        trend: {
          windowDays: 730,
          meaningfulChange: 0.5,
          description: "A T-score change of 0.5 SD or more requires review.",
        },
        contextualModifiers: ["age", "menopause status", "Z-score indication"],
        sourceTypes: ["imaging"],
        clinicianObservation: "Bone-density result outside the expected range.",
        patientMessage: "A bone-density result is outside the comparison range used here.",
      }),
      measurement({
        id: "frax",
        clinicalName: "FRAX result",
        patientFriendlyName: "Fracture-risk result",
        unit: "%",
        referenceRange: "Approved validated implementation output only",
        freshness: { outpatientDays: 365 },
        aliases: ["frax", "frax 10-year risk", "fracture risk assessment tool"],
        rule: { type: "validated-result-only" },
        sourceTypes: ["validated-calculator"],
        clinicianObservation: "Validated FRAX result received from a trusted source.",
        patientMessage: "This score is shown only when received from an approved implementation.",
        clinicianOnly: true,
        validatedResultOnly: true,
      }),
    ],
  },
  immune: {
    id: "immune",
    label: "Immune",
    shortLabel: "Immune",
    summary: "Infection-fighting cells and the body's inflammatory response.",
    anatomy: {
      represented: false,
      status: "not-represented",
      message:
        "This system is not yet represented in the 3D model. Clinical information is shown in text.",
    },
    measurements: [
      measurement({
        id: "wbc",
        clinicalName: "White blood cell count (WBC)",
        patientFriendlyName: "White blood cells",
        unit: "x10^9/L",
        referenceRange: "4-11",
        freshness: { outpatientDays: 7 },
        loincCodes: ["6690-2"],
        aliases: ["wbc", "white blood cell count", "leukocytes"],
        rule: { type: "wbc" },
        trend: { windowDays: 30 },
        sourceTypes: ["laboratory"],
        clinicianObservation: "White blood cell count outside the provisional reference range.",
        patientMessage: "A white-blood-cell result is outside the reference range used here.",
      }),
      measurement({
        id: "crp",
        clinicalName: "C-reactive protein (CRP)",
        patientFriendlyName: "Inflammation marker",
        unit: "mg/L",
        referenceRange: "<3",
        freshness: { inpatientHours: 48, outpatientDays: 7 },
        loincCodes: ["1988-5"],
        aliases: ["crp", "c-reactive protein"],
        rule: { type: "crp" },
        trend: { windowDays: 30 },
        contextualModifiers: ["nonspecific marker", "pregnancy", "recent surgery"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "Inflammation marker elevated; interpret with clinical context.",
        patientMessage: "An inflammation marker is outside the reference range used here.",
      }),
      measurement({
        id: "esr",
        clinicalName: "Erythrocyte sedimentation rate (ESR)",
        patientFriendlyName: "Inflammation marker",
        unit: "mm/hr",
        referenceRange: "Age-, sex-, and pregnancy-dependent",
        freshness: { outpatientDays: 30 },
        loincCodes: ["4537-7"],
        aliases: ["esr", "erythrocyte sedimentation rate", "sedimentation rate"],
        rule: { type: "reported-range" },
        trend: { windowDays: 30 },
        contextualModifiers: ["age", "sex", "pregnancy", "nonspecific marker"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "Inflammation marker result requires an applicable reference range.",
        patientMessage: "This inflammation marker requires interpretation by the care team.",
      }),
    ],
  },
  endocrine: {
    id: "endocrine",
    label: "Endocrine",
    shortLabel: "Endocrine",
    summary: "Hormones, metabolism, and blood sugar regulation.",
    anatomy: {
      represented: false,
      status: "not-represented",
      message:
        "This system is not yet represented in the 3D model. Clinical information is shown in text.",
    },
    measurements: [
      measurement({
        id: "hba1c",
        clinicalName: "Hemoglobin A1c (HbA1c)",
        patientFriendlyName: "Average blood sugar",
        unit: "%",
        referenceRange: "<5.7; individualized treatment target overrides",
        freshness: { outpatientDays: 90 },
        loincCodes: ["4548-4", "17856-6"],
        aliases: ["hba1c", "hemoglobin a1c", "glycated hemoglobin"],
        rule: { type: "hba1c" },
        trend: {
          windowDays: 180,
          meaningfulChange: 0.5,
          description: "A change of 0.5 percentage points or more requires review.",
        },
        contextualModifiers: ["individual treatment target", "pregnancy", "frailty"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "HbA1c result outside the provisional population reference range.",
        patientMessage: "An average-blood-sugar result is outside the range used for this view.",
      }),
      measurement({
        id: "fasting-glucose",
        clinicalName: "Fasting glucose",
        patientFriendlyName: "Fasting blood sugar",
        unit: "mg/dL",
        referenceRange: "<100",
        freshness: { inpatientHours: 24, outpatientDays: 90 },
        loincCodes: ["1558-6"],
        aliases: ["fasting glucose", "fasting blood glucose", "glucose fasting"],
        rule: { type: "fasting-glucose" },
        trend: { windowDays: 90 },
        contextualModifiers: ["fasting status", "pregnancy", "individual treatment target"],
        sourceTypes: ["laboratory", "device", "patient-reported"],
        clinicianObservation: "Fasting glucose result outside the provisional reference range.",
        patientMessage: "A fasting-blood-sugar result is outside the range used for this view.",
      }),
      measurement({
        id: "tsh",
        clinicalName: "Thyroid-stimulating hormone (TSH)",
        patientFriendlyName: "Thyroid hormone level",
        unit: "mIU/L",
        referenceRange: "0.4-4.0 general; laboratory- and pregnancy-specific range preferred",
        freshness: { outpatientDays: 365 },
        loincCodes: ["3016-3"],
        aliases: ["tsh", "thyroid stimulating hormone", "thyrotropin"],
        rule: { type: "tsh" },
        trend: { windowDays: 365 },
        contextualModifiers: ["laboratory range", "pregnancy trimester", "treatment target"],
        sourceTypes: ["laboratory"],
        clinicianObservation: "TSH result outside the applicable reference range.",
        patientMessage: "A thyroid-related result is outside the range used for this view.",
      }),
    ],
  },
});

export const PATIENT_SYSTEM_ORDER = Object.freeze([
  "overview",
  "cardiovascular",
  "respiratory",
  "digestive",
  "nervous",
  "musculoskeletal",
  "immune",
  "endocrine",
]);

export const SAFE_AUTOMATIC_ACTIONS = Object.freeze({
  "within-reference-range": "Continue monitoring",
  "within-target": "Continue monitoring",
  borderline: "Repeat test",
  abnormal: "Arrange routine follow-up",
  outdated: "Repeat test",
  "insufficient-data": null,
  "result-pending": null,
  "conflicting-data": "Clinician review required",
  "outside-supported-population": "Clinician review required",
  "clinician-review-required": "Clinician review required",
  "urgent-review": "Clinician review required",
  "critical-review": "Clinician review required",
});

export function getPatientSystemConfig(systemId) {
  return (
    PATIENT_SYSTEM_CLINICAL_CONFIG[systemId] ||
    PATIENT_SYSTEM_CLINICAL_CONFIG.overview
  );
}

const VARIANT_ANATOMY_MESSAGES = Object.freeze({
  digestive: Object.freeze({
    male:
      "Partial 3D representation: stomach/intestine, liver, and gallbladder meshes are available in this model.",
    female:
      "Partial 3D representation: stomach/intestine and liver meshes are available; a gallbladder mesh is not present in this model.",
  }),
});

export function getAnatomyAvailability(systemId, modelVariant = "male") {
  const anatomy = getPatientSystemConfig(systemId).anatomy;
  const variantMessage =
    VARIANT_ANATOMY_MESSAGES[systemId]?.[modelVariant] || null;

  return variantMessage
    ? {
        ...anatomy,
        message: variantMessage,
      }
    : anatomy;
}

export function getMeasurementConfig(measurementId) {
  for (const systemId of PATIENT_SYSTEM_ORDER) {
    const system = PATIENT_SYSTEM_CLINICAL_CONFIG[systemId];
    const found = system.measurements.find((item) => item.id === measurementId);
    if (found) return { ...found, system: systemId };
  }
  return null;
}

export function getAllMeasurementConfigs() {
  return PATIENT_SYSTEM_ORDER.flatMap((systemId) =>
    PATIENT_SYSTEM_CLINICAL_CONFIG[systemId].measurements.map((item) => ({
      ...item,
      system: systemId,
    })),
  );
}
